name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
 push:
  branches: [main]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name : "Using Yamllint"
      - uses: actions/checkout@v2
      - run: yamllint *.yaml
      - name: "Using Ansiblelint"
      - uses: actions/checkout@v2
      - run: ansible-lint *.yaml
